# This file is used to create docker images for the backend
FROM python:3.11


# Install system-level packages needed for dlib and lws
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    wget \
    git \
    curl \
    libboost-all-dev \
    libgtk2.0-dev \
    libopenblas-dev \
    liblapack-dev \
    libx11-dev \
    libgl1 \
    && apt-get clean


# Copy everything in current local dir (your gpu_worker project) into the container
COPY . /app/backend

# Set the working dir to the actual app folder
WORKDIR /app/backend

# Install Python packages
RUN pip install --upgrade pip
RUN pip install numpy
RUN pip install -r requirements.txt

COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
