apiVersion: v1
kind: Service
metadata:
  name: avatar-frontend-service
spec:
  type: NodePort # or LoadBalancer, ClusterIP as needed
  selector:
    app: avatar-frontend
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 80 # containerPort
      nodePort: 30000 # external port on Node (optional, if NodePort type)
